# model: google/gemma-3-1b-it
# trust_remote-code: true
model: /app/vllm/models/gemma-3-1b-it
served_model_name: gemma-3-1b-it
host: 0.0.0.0
port: 9000
gpu-memory-utilization: 0.35
uvicorn-log-level: debug
# download-dir: /app/vllm/models