services:
  vllm-gpu:
    build: ./vllmGPU
    container_name: vllmGPU
    volumes:
      # - /usr/lib/wsl/lib/libdxcore.so:/usr/lib/libdxcore.so # for Radeon
      # - /opt/rocm/lib/libhsa-runtime64.so.1:/opt/rocm/lib/libhsa-runtime64.so.1 # for Radeon
      - ./vllmGPU:/app/vllm
    ipc: host
    cap_add:
      # - SYS_NICE
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
    working_dir: /app/vllm
    devices:
      # - /dev/dxg # for Radeon on WSL
      - /dev/kfd
      - /dev/dri
    env_file:
      - ./__envs__/vllmGPU.env
    # command: vllm serve --config /app/vllm/configs/gemma-3-1b.yaml
    # command: vllm serve --config /app/vllm/configs/gemma-3n-E2B.yaml
    # command: bash kickVllm.sh
    # entrypoint: tail -f /dev/null
    entrypoint: vllm serve --config /app/vllm/configs/gemma4.yaml
    networks:
      - llmApp

  vllm-cpu:
    build: ./vllmCPU
    container_name: vllmCPU
    volumes:
      - ./vllmCPU:/app/vllm
    working_dir: /app/vllm
    shm_size: '1gb'
    env_file:
      - ./__envs__/vllmCPU.env
    command: --config /app/vllm/configs/embeddinggemma.yaml
    # command: --config /app/vllm/configs/functiongemma.yaml
    # entrypoint: tail -f /dev/null
    networks:
      - llmApp

  weaviate:
    build: ./weaviate
    container_name: weaviate
    volumes:
      - ./weaviate/data:/app/weaviate/data
    working_dir: /app/weaviate/data
    restart: on-failure:0
    env_file:
      - ./__envs__/weaviate.env
    networks:
      - llmApp

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend/src
    env_file:
      - ./__envs__/backend.env
    tty: true
    networks:
      - llmApp
  # secrets:
  #   weaviate_apikey:
  #     file: ./weaviate/weaviate_apikey.txt

  mcp-server:
    build: ./backend
    container_name: mcp-server
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend/src/mcpserver
    ports:
      - 8888:8000
    env_file:
      - ./__envs__/backend.env
    entrypoint: uvicorn MCPServer:app --host 0.0.0.0 --port 8000
    # entrypoint: tail -f /dev/null
    networks:
      - llmApp

networks:
  llmApp:
    driver: bridge
