services:
  # vllm-gpu:
  #   build: ./vllmGPU
  #   container_name: vllmGPU
  #   volumes:
  #     - /usr/lib/wsl/lib/libdxcore.so:/usr/lib/libdxcore.so # for Radeon
  #     - /opt/rocm/lib/libhsa-runtime64.so.1:/opt/rocm/lib/libhsa-runtime64.so.1 # for Radeon
  #     - ./vllmGPU:/app/vllm
  #   ipc: host
  #   cap_add:
  #     # - SYS_NICE
  #     - SYS_PTRACE
  #   security_opt:
  #     - seccomp:unconfined
  #   group_add:
  #     - video
  #   working_dir: /app/vllm
  #   devices:
  #     - /dev/dxg # for Radeon on WSL
  #   env_file:
  #     - ./__envs__/vllmGPU.env
  #   command: vllm serve --config /app/vllm/configs/gemma-3-1b.yaml
  #   # command: vllm serve --config ./gemma-3n-E2B.yaml
  #   # command: tail -f /dev/null
  #   networks:
  #     - llmApp
  vllm-cpu:
    build: ./vllmCPU
    container_name: vllmCPU
    volumes:
      - ./vllmCPU:/app/vllm
    working_dir: /app/vllm
    shm_size: '1gb'
    env_file:
      - ./__envs__/vllmCPU.env
    # command: vllm serve --config /app/vllm/models/gemma-3-1b.yaml
    command: tail -f /dev/null
    networks:
      - llmApp
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    env_file:
      - ./__envs__/backend.env
    tty: true
    networks:
      - llmApp

networks:
  llmApp:
    driver: bridge
