# FROM python:3.12-slim

# RUN apt-get update && apt-get install -y gcc-12 g++-12 libnuma-dev python3-dev git
# RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12

# WORKDIR /app
# RUN mkdir vllm_source

# RUN git clone https://github.com/vllm-project/vllm.git vllm_source
# WORKDIR /app/vllm_source

# RUN pip install --upgrade pip
# RUN pip install -v -r requirements/cpu-build.txt --extra-index-url https://download.pytorch.org/whl/cpu
# RUN pip install -v -r requirements/cpu.txt --extra-index-url https://download.pytorch.org/whl/cpu

# ENV VLLM_TARGET_DEVICE=cpu
# RUN pip install . --no-build-isolation
FROM public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:v0.13.0
ENV VLLM_CPU_KVCACHE_SPACE=4